LoginResponseData:
  path: webservice/login
  properties:
    accessToken: string
    refreshToken: string
LoginResponse:
  path: webservice/login
  properties:
    data: LoginResponseData
LoginRequest:
  path: webservice/login
  properties:
    username: string
    password: string
    deviceId: string
Brewery:
  path: webservice/beer
  properties:
    id: string
    name: string
    address: string
    city: string
    country: string
Beer:
  path: webservice/beer
  properties:
    id: string
    name: string
    rating: int
    thumbImageUrl: string
    imageUrl: string
    brewery: Brewery?
BeerResponse:
  path: webservice/beer
  properties:
    data: List<Beer>
BreweryResponse:
  path: webservice/beer
  properties:
    data: List<Brewery>
BeerWithBrewery:
  path: webservice/beer
  properties:
    beer: Beer
    brewery: Brewery?
SortOption:
  path: webservice/beer
  type: enum
  properties:
    nameAscending:
    ratingDescending:
    ratingAscending:
GroupOption:
  path: webservice/beer
  type: enum
  properties:
    brewery:
    rating:
    none: