// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2eCd62w__zUygCAiGHlo_yWeXpQxuv0',
    appId: '1:923510428032:web:496997ea4ffe972e99f165',
    messagingSenderId: '923510428032',
    projectId: 'beer-app-8634a',
    authDomain: 'beer-app-8634a.firebaseapp.com',
    storageBucket: 'beer-app-8634a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOkCIQSxz4A-6X4iebHN06RtAVkMDgq0c',
    appId: '1:923510428032:android:d7e34353a49c2c1299f165',
    messagingSenderId: '923510428032',
    projectId: 'beer-app-8634a',
    storageBucket: 'beer-app-8634a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyHyr9iDmK4DVVxe7eX9zZvN6_q-RdhM',
    appId: '1:923510428032:ios:c2b2f26db2c0c79d99f165',
    messagingSenderId: '923510428032',
    projectId: 'beer-app-8634a',
    storageBucket: 'beer-app-8634a.appspot.com',
    iosClientId: '923510428032-sukdq6rrekb4d9t4s4a1fhkii4vi7dq9.apps.googleusercontent.com',
    iosBundleId: 'be.example.beerapp.dev',
  );
}
